config/routes.rb
Rails.application.routes.draw do
  resources :bookracks
  devise_for :users, :controllers => {
    :sessions      => 'users/sessions',
    :registrations => 'users/registrations'
  }

  get    'top'                          => 'bookracks#top' , as: :top_bookrack

  get    'books'          => 'books#index'   , as: :books
  post   'books'          => 'books#create'
  get    'books/new'      => 'books#new'     , as: :new_book
  get    'books/:id/edit' => 'books#edit'    , as: :edit_book
  get    'books/:id'      => 'books#show'    , as: :book
  patch  'books/:id'      => 'books#update'
  put    'books/:id'      => 'books#update'
  delete 'books/:id'      => 'books#destroy'

  root to: "bookracks#top"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :bookrack_books
  has_many :bookracks, through: :bookrack_books
end

app/models/bookrack.rb
class Bookrack < ActiveRecord::Base
  belongs_to :user

  has_many :bookrack_books
  has_many :books, through: :bookrack_books
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/bookracks_controller.rb
class BookracksController < ApplicationController
  before_filter :authenticate_user!


  # GET /bookracks/top
  def top
    @user = User.find(current_user.id)
  end

  # GET /bookracks
  def index
    @bookracks = Bookrack.where(:user_id => current_user.id).all
  end

  # GET /bookracks/:id
  def show
    @bookrack = Bookrack.find(params[:id])
    @books = Book.where(:bookrack_id => params[:id]).all
  end

  # GET /bookracks/new
  def new
    @bookrack = Bookrack.new
  end

  # GET /bookracks/:id/edit
  def edit
    @bookrack = Bookrack.find(params[:id])
  end


  # POST /bookracks
  def create
    @bookrack = Bookrack.new(bookrack_params)
    @bookrack.user_id = current_user.id
    respond_to do |format|
      if @bookrack.save
        format.html { redirect_to @bookrack, notice: 'Created' }
#        format.csv
#        format.json
      else
        format.html { render :new }
      end
    end
  end


  # PATCH/PUT /bookracks/:id
  def update
    @bookrack = Bookrack.find(params[:id])
    respond_to do |format|
      if @bookrack.update(bookrack_params)
        format.html { redirect_to @bookrack, notice: 'Bookrack was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /bookracks/:id
  def destroy
    @bookrack = Bookrack.find(params[:id])
    @bookrack.destroy
    respond_to do |format|
      format.html { redirect_to bookracks_url, notice: 'Bookrack was successfully destroyed.' }
    end
  end





  private
  def bookrack_params
    params.require(:bookrack).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!


  # GET /books
  def index
    @books     = []
    @bookracks = Bookrack.where(:user_id => current_user.id).all
    @bookracks.each do |bookrack|
      @books << Book.where(:bookrack_id => bookrack.id).all
    end
    @books = @books.flatten
  end

  # GET /books/:id
  def show
    @book     = Book.find(params[:id])
    @bookrack = Bookrack.find(@book.bookrack_id)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/:id/edit
  def edit
    @book = Book.find(params[:id])
  end


  # POST /books
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Created' }
#        format.csv
#        format.json
      else
        format.html { render :new }
      end
    end
  end


  # PATCH/PUT /books/:id
  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /books/:id
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
    end
  end





  private
  def book_params
    params.require(:book).permit(:name, :author, :category, :memo, :bookrack_id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create
    super
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    super
  end

  def create
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookracks_helper.rb
module BookracksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/bookracks/_form.html.erb
<%= form_for(@bookrack) do |f| %>
  <% if @bookrack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookrack.errors.count, "error") %> prohibited this bookrack from being saved:</h2>

      <ul>
      <% @bookrack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookracks/edit.html.erb
<h1>Editing bookrack</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookrack %> |
<%= link_to 'Back', bookracks_path %>

app/views/bookracks/index.html.erb
<div class="top-container">
  <h2>Listing bookracks</h2>
</div>

<table>
  <tbody>
    <% @bookracks.each do |bookrack| %>
      <tr>
        <td><%= bookrack.name %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Show', bookrack %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<footer>
<%= link_to '本棚を追加　　 : Add new Bookrack', new_bookrack_path %>
</footer>

app/views/bookracks/new.html.erb
<h1>New bookrack</h1>

<%= render 'form' %>

<%= link_to 'Back', bookracks_path %>

app/views/bookracks/show.html.erb
<h2><%= @bookrack.name %></h2>
<p id="notice"><%= notice %></p>
<%= link_to 'この本棚を削除 : Delete', @bookrack, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'この本棚を編集 : Edit Bookrack name', edit_bookrack_path(@bookrack) %>
<br>
<%= '----------------------' %>
<br>

<table>
  <tbody>
    <tr>
      <th><strong><%= 'Book Name' %></strong></th>
      <th> &nbsp; </th>
      <th><strong><%= 'Book Author' %></strong></th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td> &nbsp; </td>
        <td><%= book.author %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Show', book %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>
<br>
<br>
<br>


<%= link_to '本を追加　　　 : Add new Book', new_book_path %>
<br>
<%= link_to '本一覧　　　　 : Show Book List', books_path %>
<br>
<%= link_to '本棚一覧に戻る : Back to bookrack list', bookracks_path %>

app/views/bookracks/top.html.erb
<div class="top-container">
  <div class="top-userinfo">
    <h5>
      <table>
        <tbody>
          <%= 'login user : ' %>
          <%= @user.email %>
          <br>
          <%= link_to 'ユーザ情報変更 : Edit user info', edit_user_registration_path %>
        </tbody>
      </table>
    </h5>
  </div>
  <h2>Welcome to Hondana</h2>
</div>

<br>

<%= link_to '本棚一覧 : Bookrack List', bookracks_path %>
<br>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <input id="book_memo" name="book[memo]" size="50" type="text" />
  </div>
  <div class="field">
    <%= f.label :bookrack %><br>
    <%= f.collection_select :bookrack_id, Bookrack.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back to book list', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th> &nbsp; </th>
      <th>BookrackName</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td> &nbsp; </td>
        <td><%= @bookracks.find(book.bookrack_id).name %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Show', book %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td> &nbsp; </td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>
<br>

<%= link_to 'Add new Book', new_book_path %>
<br>
<%= link_to 'Back to Bookrack list', bookracks_path %>
<br>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back to book list', books_path %>

app/views/books/show.html.erb
<h2><%= @book.name %></h2>
<p id="notice"><%= notice %></p>
<%= '----------------------' %>



<table>
  <tbody>
      <tr>
        <td><strong>Author</strong></td>
        <td> &nbsp;:&nbsp; </td>
        <td><%= @book.author %></td>
        <td> &nbsp; </td>
      </tr>
      <tr>
        <td><strong>Category</strong></td>
        <td> &nbsp;:&nbsp; </td>
        <td><%= @book.category %></td>
        <td> &nbsp; </td>
      </tr>
      <tr>
        <td><strong>Memo</strong></td>
        <td> &nbsp;:&nbsp; </td>
        <td><%= @book.memo %></td>
        <td> &nbsp; </td>
      </tr>
      <tr>
        <td><strong>Bookrack</strong></td>
        <td> &nbsp;:&nbsp; </td>
        <td><%= @bookrack.name %></td>
        <td> &nbsp; </td>
      </tr>
  </tbody>
</table>


<br>
<br>
<br>
<br>
<br>


<%= link_to 'Add new Book', new_book_path %>
<br>
<%= link_to 'Edit this book info', edit_book_path(@book) %>
<br>
<%= link_to 'Back to this bookrack', bookrack_path(@bookrack) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Hondana</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>



  <body>
    <header class="navbar navbar-default" style="background:#000000;" role="navigation">
      <div class="navbar-header">
        <%= link_to 'Hondana', root_path, class: 'navbar-brand'%>

        <% if user_signed_in?%>
          <div class="navbar-brand">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="navbar-brand">
          <%= link_to 'Login', new_user_session_path %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

  </body>
</html>